// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlNjzbonYTOwiUcPHv5NeD4gnVwXfrlE',
    appId: '1:185801379566:web:10402d5725a4176e4a2dff',
    messagingSenderId: '185801379566',
    projectId: 'financemanager-244f9',
    authDomain: 'financemanager-244f9.firebaseapp.com',
    storageBucket: 'financemanager-244f9.firebasestorage.app',
    measurementId: 'G-9MPKJJCFTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1XswzDTLbtQs04LS8T0TVC7PgrGsr6Ig',
    appId: '1:185801379566:android:a43717dc5a994bba4a2dff',
    messagingSenderId: '185801379566',
    projectId: 'financemanager-244f9',
    storageBucket: 'financemanager-244f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPS4QgmYLwVjfEmFJ1mtrgzsllgEmDuw',
    appId: '1:185801379566:ios:b25804e60e6bdc234a2dff',
    messagingSenderId: '185801379566',
    projectId: 'financemanager-244f9',
    storageBucket: 'financemanager-244f9.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPS4QgmYLwVjfEmFJ1mtrgzsllgEmDuw',
    appId: '1:185801379566:ios:b25804e60e6bdc234a2dff',
    messagingSenderId: '185801379566',
    projectId: 'financemanager-244f9',
    storageBucket: 'financemanager-244f9.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOlNjzbonYTOwiUcPHv5NeD4gnVwXfrlE',
    appId: '1:185801379566:web:b6af5a65d34988a24a2dff',
    messagingSenderId: '185801379566',
    projectId: 'financemanager-244f9',
    authDomain: 'financemanager-244f9.firebaseapp.com',
    storageBucket: 'financemanager-244f9.firebasestorage.app',
    measurementId: 'G-HTFP0L6ZK4',
  );
}
